name: Build Fabric JAR

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug tree
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type f | sort

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build mod jar
        run: ./gradlew build remapJar --no-daemon

      - name: List jars
        run: ls -la build/libs || true

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: yakusha-client-jar
          path: build/libs/*.jar
          if-no-files-found: error
